// This file is automatically generated by qtc from "template.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line template.qtpl:1
package main

//line template.qtpl:2
import "time"

//line template.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template.qtpl:5
type Page interface {
	//line template.qtpl:5
	Title() string
	//line template.qtpl:5
	StreamTitle(qw422016 *qt422016.Writer)
	//line template.qtpl:5
	WriteTitle(qq422016 qtio422016.Writer)
	//line template.qtpl:5
	Body() string
	//line template.qtpl:5
	StreamBody(qw422016 *qt422016.Writer)
	//line template.qtpl:5
	WriteBody(qq422016 qtio422016.Writer)
//line template.qtpl:5
}

//line template.qtpl:11
func StreamMainHTML(qw422016 *qt422016.Writer, p Page) {
	//line template.qtpl:11
	qw422016.N().S(`
    <!doctype html>
<html>
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<link rel="stylesheet" type="text/css" href="/assets/css/main.css">				
	</head>
	<body>
	<h1 class="page-title">
		`)
	//line template.qtpl:20
	qw422016.N().S(p.Title())
	//line template.qtpl:20
	qw422016.N().S(`
	</h1>
	`)
	//line template.qtpl:22
	qw422016.N().S(p.Body())
	//line template.qtpl:22
	qw422016.N().S(`    
	</body>
</html>
`)
//line template.qtpl:25
}

//line template.qtpl:25
func WriteMainHTML(qq422016 qtio422016.Writer, p Page) {
	//line template.qtpl:25
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template.qtpl:25
	StreamMainHTML(qw422016, p)
	//line template.qtpl:25
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:25
}

//line template.qtpl:25
func MainHTML(p Page) string {
	//line template.qtpl:25
	qb422016 := qt422016.AcquireByteBuffer()
	//line template.qtpl:25
	WriteMainHTML(qb422016, p)
	//line template.qtpl:25
	qs422016 := string(qb422016.B)
	//line template.qtpl:25
	qt422016.ReleaseByteBuffer(qb422016)
	//line template.qtpl:25
	return qs422016
//line template.qtpl:25
}

//line template.qtpl:29
type MainPage struct {
	Records []ExceptionRecord
}

type ExceptionRecord struct {
	CreatedAt           time.Time
	Class, Message, Ref string
}

type StackTracePage struct {
	Class, Message string
	StackTrace     [][]string
}

//line template.qtpl:45
func (p *MainPage) StreamTitle(qw422016 *qt422016.Writer) {
	//line template.qtpl:45
	qw422016.N().S(`
	Ошибки
`)
//line template.qtpl:47
}

//line template.qtpl:47
func (p *MainPage) WriteTitle(qq422016 qtio422016.Writer) {
	//line template.qtpl:47
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template.qtpl:47
	p.StreamTitle(qw422016)
	//line template.qtpl:47
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:47
}

//line template.qtpl:47
func (p *MainPage) Title() string {
	//line template.qtpl:47
	qb422016 := qt422016.AcquireByteBuffer()
	//line template.qtpl:47
	p.WriteTitle(qb422016)
	//line template.qtpl:47
	qs422016 := string(qb422016.B)
	//line template.qtpl:47
	qt422016.ReleaseByteBuffer(qb422016)
	//line template.qtpl:47
	return qs422016
//line template.qtpl:47
}

//line template.qtpl:49
func (p *MainPage) StreamBody(qw422016 *qt422016.Writer) {
	//line template.qtpl:49
	qw422016.N().S(`
	<div class="center-block-wrapper">
		<table class="errors-log">
		<tbody>		
			`)
	//line template.qtpl:53
	for _, r := range p.Records {
		//line template.qtpl:53
		qw422016.N().S(`
				<tr>
					<td>
						`)
		//line template.qtpl:56
		qw422016.E().S(r.CreatedAt.Format("02.01.2006 15:04:05"))
		//line template.qtpl:56
		qw422016.N().S(`
					</td>
					<td><b>`)
		//line template.qtpl:58
		qw422016.E().S(r.Class)
		//line template.qtpl:58
		qw422016.N().S(`</b></td>
					<td>`)
		//line template.qtpl:59
		qw422016.E().S(r.Message)
		//line template.qtpl:59
		qw422016.N().S(`</td>
					<td>
						<a class="btn-link" href="`)
		//line template.qtpl:61
		qw422016.E().S(r.Ref)
		//line template.qtpl:61
		qw422016.N().S(`">></a>
					</td>
					
				</tr>			
			`)
		//line template.qtpl:65
	}
	//line template.qtpl:65
	qw422016.N().S(`
		</tbody>
		</table>
	</div>

    
	</body>
`)
//line template.qtpl:72
}

//line template.qtpl:72
func (p *MainPage) WriteBody(qq422016 qtio422016.Writer) {
	//line template.qtpl:72
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template.qtpl:72
	p.StreamBody(qw422016)
	//line template.qtpl:72
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:72
}

//line template.qtpl:72
func (p *MainPage) Body() string {
	//line template.qtpl:72
	qb422016 := qt422016.AcquireByteBuffer()
	//line template.qtpl:72
	p.WriteBody(qb422016)
	//line template.qtpl:72
	qs422016 := string(qb422016.B)
	//line template.qtpl:72
	qt422016.ReleaseByteBuffer(qb422016)
	//line template.qtpl:72
	return qs422016
//line template.qtpl:72
}

//line template.qtpl:74
func (p *StackTracePage) StreamTitle(qw422016 *qt422016.Writer) {
	//line template.qtpl:74
	qw422016.N().S(`
	`)
	//line template.qtpl:75
	qw422016.E().S(p.Class)
	//line template.qtpl:75
	qw422016.N().S(`
`)
//line template.qtpl:76
}

//line template.qtpl:76
func (p *StackTracePage) WriteTitle(qq422016 qtio422016.Writer) {
	//line template.qtpl:76
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template.qtpl:76
	p.StreamTitle(qw422016)
	//line template.qtpl:76
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:76
}

//line template.qtpl:76
func (p *StackTracePage) Title() string {
	//line template.qtpl:76
	qb422016 := qt422016.AcquireByteBuffer()
	//line template.qtpl:76
	p.WriteTitle(qb422016)
	//line template.qtpl:76
	qs422016 := string(qb422016.B)
	//line template.qtpl:76
	qt422016.ReleaseByteBuffer(qb422016)
	//line template.qtpl:76
	return qs422016
//line template.qtpl:76
}

//line template.qtpl:79
func (p *StackTracePage) StreamBody(qw422016 *qt422016.Writer) {
	//line template.qtpl:79
	qw422016.N().S(`
	<a class="btn-link" href="/">
		< Назад
	</a>

	<div class="center-block-wrapper">
		<div class="exception-message">			
			`)
	//line template.qtpl:86
	qw422016.E().S(p.Message)
	//line template.qtpl:86
	qw422016.N().S(`
		</div>
	</div>

	<div class="center-block-wrapper">
		<table>
		<tbody>
			`)
	//line template.qtpl:93
	for _, line := range p.StackTrace {
		//line template.qtpl:93
		qw422016.N().S(`
				<tr>
					`)
		//line template.qtpl:95
		for _, cell := range line {
			//line template.qtpl:95
			qw422016.N().S(`
						<td>`)
			//line template.qtpl:96
			qw422016.E().S(cell)
			//line template.qtpl:96
			qw422016.N().S(`</td>
					`)
			//line template.qtpl:97
		}
		//line template.qtpl:97
		qw422016.N().S(`
				</tr>			
			`)
		//line template.qtpl:99
	}
	//line template.qtpl:99
	qw422016.N().S(`
		</tbody>
		</table>
	</div>

	
	

`)
//line template.qtpl:107
}

//line template.qtpl:107
func (p *StackTracePage) WriteBody(qq422016 qtio422016.Writer) {
	//line template.qtpl:107
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line template.qtpl:107
	p.StreamBody(qw422016)
	//line template.qtpl:107
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:107
}

//line template.qtpl:107
func (p *StackTracePage) Body() string {
	//line template.qtpl:107
	qb422016 := qt422016.AcquireByteBuffer()
	//line template.qtpl:107
	p.WriteBody(qb422016)
	//line template.qtpl:107
	qs422016 := string(qb422016.B)
	//line template.qtpl:107
	qt422016.ReleaseByteBuffer(qb422016)
	//line template.qtpl:107
	return qs422016
//line template.qtpl:107
}
