// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package data

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type gasTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *gasTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("gas").
func (v *gasTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *gasTableType) Columns() []string {
	return []string{"gas_name", "code"}
}

// NewStruct makes a new struct for that view or table.
func (v *gasTableType) NewStruct() reform.Struct {
	return new(Gas)
}

// NewRecord makes a new record for that table.
func (v *gasTableType) NewRecord() reform.Record {
	return new(Gas)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *gasTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// GasTable represents gas view or table in SQL database.
var GasTable = &gasTableType{
	s: parse.StructInfo{Type: "Gas", SQLSchema: "", SQLName: "gas", Fields: []parse.FieldInfo{{Name: "GasName", Type: "string", Column: "gas_name"}, {Name: "Code", Type: "uint8", Column: "code"}}, PKFieldIndex: 0},
	z: new(Gas).Values(),
}

// String returns a string representation of this struct or record.
func (s Gas) String() string {
	res := make([]string, 2)
	res[0] = "GasName: " + reform.Inspect(s.GasName, true)
	res[1] = "Code: " + reform.Inspect(s.Code, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Gas) Values() []interface{} {
	return []interface{}{
		s.GasName,
		s.Code,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Gas) Pointers() []interface{} {
	return []interface{}{
		&s.GasName,
		&s.Code,
	}
}

// View returns View object for that struct.
func (s *Gas) View() reform.View {
	return GasTable
}

// Table returns Table object for that record.
func (s *Gas) Table() reform.Table {
	return GasTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Gas) PKValue() interface{} {
	return s.GasName
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Gas) PKPointer() interface{} {
	return &s.GasName
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Gas) HasPK() bool {
	return s.GasName != GasTable.z[GasTable.s.PKFieldIndex]
}

// SetPK sets record primary key.
func (s *Gas) SetPK(pk interface{}) {
	if i64, ok := pk.(int64); ok {
		s.GasName = string(i64)
	} else {
		s.GasName = pk.(string)
	}
}

// check interfaces
var (
	_ reform.View   = GasTable
	_ reform.Struct = (*Gas)(nil)
	_ reform.Table  = GasTable
	_ reform.Record = (*Gas)(nil)
	_ fmt.Stringer  = (*Gas)(nil)
)

func init() {
	parse.AssertUpToDate(&GasTable.s, new(Gas))
}
